---
# (c) Copyright IBM Corporation
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


- name: Ensure the custom configuration directory exists
  become: true
  ansible.builtin.file:
    path: "/etc/ssh/sshd_config.d"
    state: directory
    owner: root
    group: root

- name: Add neerali sshd configuration
  become: true
  ansible.builtin.copy:
    src: files/50-neerali-sshd.conf
    dest: /etc/ssh/sshd_config.d/neerali-sshd.conf
    owner: root
    group: root
    mode: '0644'
  notify: 'Restart sshd'

# We are forcing a notification as it might be too late when all tasks in
# the play completes.
- name: Force the restart
  ansible.builtin.meta: flush_handlers
