# pages.github configuration for jekyll
source        : _pages
site          : _site
exclude       : ['*.yml', '*.yaml', '*.j2']
encoding      : "utf-8"
mardown_ext   : "md"

markdown      : kramdown
highlighter   : rouge
lsi           : false
incremental   : false
