---
namespace: neerali
name: general
version: "1.0.0"
readme: README.md

authors:
  - psathyan (https://github.com/psathyan)

description: "A framework for continuous testing of Ceph."
license: []
license_file: 'LICENSE'

tags:
  - ci
  - linux
  - tools

dependencies:
  'git+https://github.com/ansible-collections/community.general': 'main'
  'git+https://github.com/ansible-collections/ansible.posix': 'main'
  'git+https://github.com/ansible-collections/community.crypto': 'main'
  'git+https://github.com/openstack/ansible-config_template': 'master'

repository: https://github.com/psathyan/neerali.git
