---
- name: Create IBM Cloud servers
  hosts: localhost
  tasks:
    - name: Create server instance
      neerali.general.ibmvpc_server:
        access_key: n2nCHGCl5gElhuFPy6C4WrQYKHupuNu4G43tmgPO4eiP
        state: present
        name: "neerali-ibmc-test-server-{{ item }}"
        image: ibm-redhat-9-4-minimal-amd64-1
        network: sn-20240306-02
        ssh_keys:
          - venkat-public-key
          - ceph-qe-jenkins
        vpc: ceph-qe-vpc
        profile: bx2-2x8
        security_group: flick-outgoing-rejoicing-broadways
        zone: us-south-2
        dns_zone: dall.qe.ceph.local
        resource_group: Ceph-qe
        volume_size: 30
        volume_count: 2
        user_data: "{{ neerali_systems_layout['cloud_init'] }}"
      async: 600
      poll: 0
      register: _neerali_ibmc_async_servers
      loop: "{{ range(1, 5) | list }}"

    - name: Wait for all computes to be created
      ansible.builtin.async_status:
        jid: "{{ item.ansible_job_id }}"
      register: _neerali_ibmc_systems
      until: _neerali_ibmc_systems.finished
      retries: 60
      delay: 10
      loop: "{{ _neerali_ibmc_async_servers.results }}"
      loop_control:
        label: "{{ item.ansible_job_id }}"

    # - name: Delete server instance
    #   ibmvpc_server:
    #     access_key: n2nCHGCl5gElhuFPy6C4WrQYKHupuNu4G43tmgPO4eiP
    #     state: absent
    #     name: "neerali-ibmc-test-server-{{ item }}"
    #   loop: "{{ range(1, 5) | list }}"
