---
- name: Gather IBM Cloud volumes facts
  hosts: localhost
  tasks:
    - name: Retrieve volumes information for a specific instance
      ibmvpc_volume_facts:
        access_key: "n2nCHGCl5gElhuFPy6C4WrQYKHupuNu4G43tmgPO4eiP"
        service_url: "https://xxxx.iaas.cloud.ibm.com/v1"
        instance_id: "neerali-jump-vm"
      register: volumes_info

    - name: Display volume information
      debug:
        var: volumes_info