---
collections:
  - name: https://github.com/ansible-collections/ansible.posix
    type: git
  - name: https://github.com/ansible-collections/ansible.utils
    type: git
  - name: https://github.com/ansible-collections/community.general
    type: git
  - name: https://github.com/openstack/ansible-config_template
    type: git
