---
# (c) Copyright IBM Corporation
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


- name: Ensure workspace exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
  loop:
    - "{{ neerali_teuthology_basedir }}"
    - "{{ neerali_teuthology_artifactdir }}"
    - "{{ neerali_teuthology_logdir }}"
  loop_control:
    label: "{{ item }}"

- name: Install the required prerequisites
  become: true
  ansible.builtin.package:
    name: "{{ neerali_teuthology_packages }}"

# Don't replace the configuration if contents are found to different.
# This is to avoid clobbering of existing file that may have more
# details and managed outside the purview of this run.
- name: Ensure teuthology configuration file exists.
  become: true
  ansible.builtin.template:
    src: "templates/teuthology.yaml.j2"
    dest: "/etc/teuthology.yaml"
    owner: root
    group: root
    mode: "0644"
    force: false

- name: Clone the repository
  ansible.builtin.git:
    dest: "{{ neerali_teuthology_artifactdir }}"
    repo: "{{ neerali_teuthology_repo.url }}"
    single_branch: true
    version: "{{ neerali_teuthology_repo.branch }}"

- name: Install packaging as a pre-requisite
  ansible.builtin.pip:
    name: "packaging"
    virtualenv: "{{ neerali_teuthology_artifactdir }}/venv"
    virtualenv_command: "python3 -m venv"

- name: Install packages from requirements
  ansible.builtin.pip:
    extra_args: "--use-pep517"
    requirements: "{{ neerali_teuthology_artifactdir ~ '/requirements.txt'}}"
    virtualenv: "{{ neerali_teuthology_artifactdir }}/venv"

- name: Install teuthology in editable mode
  ansible.builtin.pip:
    chdir: "{{ neerali_teuthology_artifactdir }}"
    editable: true
    name: ".[test]"
    virtualenv: "{{ neerali_teuthology_artifactdir }}/venv"

- name: Reimage nodes
  when:
    - neerali_systems_layout is defined
    - neerali_systems_layout.baremetal is defined
    - neerali_teuthology_reimage | bool
  ansible.builtin.include_tasks: reimage.yaml
