---
# (c) Copyright IBM Corporation
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


- name: Add ceph's public key to all nodes participating in the cluster
  when:
    - >-
      neerali_ceph_config[neerali_ceph_cluster_name]['bootstrap']['ssh-public-key']
      is not defined
  vars:
    _hosts_hosts: >-
      {{
        neerali_ceph_nodes_public_ips[neerali_ceph_cluster_name] |
        dict2items |
        map(attribute='key')
      }}
  block:
    - name: Read ceph's public key
      ansible.builtin.slurp:
        src: "/etc/ceph/ceph.pub"
      register: _ceph_pub_key

    - name: Allow access to all nodes for ceph's ssh key.
      ansible.posix.authorized_key:
        key: "{{ _ceph_pub_key['content'] | b64decode }}"
        user: root
        state: present
      delegate_to: "{{ item }}"
      loop: "{{ _hosts_hosts }}"
      loop_control:
        label: "{{ item }}"

- name: Add the identified hosts to the cluster
  vars:
    _log_file: "{{ neerali_ceph_logdir }}/add_host_{{ item }}.success"
    _labels: >-
      {{
        neerali_systems_provisioned |
        selectattr('name', 'equalto', item) |
        selectattr('cluster', 'equalto', neerali_ceph_cluster_name) |
        map(attribute='roles') |
        first |
        join(',')
      }}
    _host_public_net: >-
      {{
        neerali_ceph_nodes_public_ips[neerali_ceph_cluster_name][item]
      }}
  ansible.builtin.shell:
    cmd: |
      set -euxo pipefail
      ceph orch host add {{ item }} {{ _host_public_net }} --labels {{ _labels }} | \
        tee {{ neerali_ceph_logdir }}/add_host_{{ item }}.log
      touch {{ _log_file }}
    creates: "{{ _log_file }}"
  loop: >-
    {{
      neerali_systems_provisioned |
      selectattr('cluster', 'equalto', neerali_ceph_cluster_name) |
      rejectattr('client', 'defined') |
      map(attribute='name')
    }}
  loop_control:
    label: "{{ item }}"
