---
# (c) Copyright IBM Corporation
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.


- name: Prepare the host map
  ansible.builtin.set_fact:
    _host_map: >-
      {% set _map = {}                                                                     -%}
      {% set _clust_name = hostvars[inventory_hostname]['neerali_ceph_cluster_name']       -%}
      {% set _net = hostvars[inventory_hostname][_clust_name][neerali_ceph_public_network] -%}
      {% for _node in hostvars                                                             -%}
      {%     set _ips = _node['all_ipv4_addresses'] + _node['all_ipv6_addresses']          -%}
      {%     set _hcn = _node['neerali_ceph_cluster_name']                                 -%}
      {%     for _ip in _ips                                                               -%}
      {%         if (_ip is ansible.builtin.in_network _net) and (_hcn == _clust_name)     -%}
      {%             set _ = _map | combine({_node['hostname']: _ip})                      -%}
      {%         endif                                                                     -%}
      {%      endfor                                                                       -%}
      {% endfor                                                                            -%}
      {{ _map }}

- name: Print the gather host map
  ansible.builtin.debug:
    var: _host_map

- name: Add the identified hosts to the cluster
  var:
    _log_file: "{{ neerali_ceph_logdir }}/add_host_{{ item.key }}.success"
  ansible.builtin.shell: |
    set -o pipefail
    ceph orch hosts add {{ item.key }} {{ item.value }}
    touch _log_file
  creates: "{{ _log_file }}"
  loop: "{{ _host_map | dict2items }}"
  loop_control:
    label: "{{ item.key }}"
