---
# (c) Copyright IBM Corporation
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

# The purpose of this task is to gather the monitor IP address


- name: Gather the monitor address
  when:
    - neerali_ceph_public_network is defined
    - item is ansible.utils.in_network neerali_ceph_public_network
  ansible.builtin.set_fact:
    _bootstrap_args: >-
      {{
        _bootstrap_args | combine({'mon-ip': item})
      }}
  loop: >-
    {{
      neerali_ceph_public_network is ansible.utils.ipv4 |
      ternary(ansible_all_ipv4_addresses, ansible_all_ipv6_addresses)
    }}

- name: Setting monitor IP address to default IPv4 address
  when:
    - neerali_ceph_public_network is not defined
  ansible.builtin.set_fact:
    _bootstrap_args: >-
      {{
        _bootstrap_args | combine({'mon-ip': ansible_default_ipv4.address})
      }}
    neerali_ceph_public_network: "{{ ansible_default_ipv4.network }}"
