---
# Molecule config
driver:
  name: default
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local

log: true

platforms:
  - name: instance
    environment:
      http_proxy: "{{ lookup('env', 'http_proxy') }}"
      https_proxy: "{{ lookup('env', 'https_proxy') }}"

provisioner:
  name: ansible
  config_options:
    defaults:
      fact_caching: yaml
      fact_caching_connection: /tmp/molecule/facts
      remote_tmp: /tmp
      local_tmp: /tmp
  log: true
  env:
    ANSIBLE_STDOUT_CALLBACK: yaml
    ANSIBLE_ROLES_PATH: "${NEERALI_ROLES_PATH:-~/.ansible/roles}"
    ANSIBLE_LIBRARY: "${NEERALI_LIBRARY:-/usr/share/ansible/plugins/modules}"
    ANSIBLE_FILTER_PLUGINS: "${NEERALI_FILTER_PLUGINS:-/usr/share/ansible/plugins/filter}"
    ANSIBLE_ACTION_PLUGINS: "${NEERALI_ACTION_PLUGINS:-/usr/share/ansible/plugins/action}"

scenario:
  test_sequence:
    - prepare
    - converge
    - cleanup

verifier:
  name: ansible
